# Health check for the kitchen service
GET {{HostAddress}}/kitchen-service/health

###

# Accept the new order
@OrderId=602c9ebf-ba80-4bc5-8b5d-bb66c04b168a
PUT {{HostAddress}}/kitchen-service/api/orders/{{OrderId}}/accept

###


# Reject one order

PUT {{HostAddress}}/kitchen-service/api/orders/{{OrderId}}/reject

###
