apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress
  labels:
    app: fastTechFoods
    service: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
        - name: fasttechfoods-mongoexpress
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongodb-svc"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "mongoexpress_user"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "mongoexpress_password"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"