apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: fastTechFoods
    service: database
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
