apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  labels:
    app: fastTechFoods
    service: gateway
spec:
  selector:
    app: fastTechFoods
    service: gateway
  #type: NodePort
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 31000