apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: fastTechFoods
    service: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "15692"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: fasttechfoods-rabbitmq
          image: rabbitmq:management-alpine
          ports:
            - containerPort: 5672   # conexão AMQP
            - containerPort: 15672  # painel web
            - containerPort: 15692  # Prometheus exporter
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ_PROMETHEUS
              value: "true"
          readinessProbe:
            httpGet:
              path: /api/healthchecks/node
              port: 15672
              httpHeaders:
                - name: Authorization
                  value: Basic Z3Vlc3Q6Z3Vlc3Q= # base64(guest:guest)
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"